import type {Rule, RuleCondition} from '../api/rules'

type Pair = readonly [string, string]
export const ruleLabels: Record<string, Record<string, Pair>> = {
    condition: {
 test:['Expression test','计算条件'],
        always: ['Always match', '始终匹配'],
        all: ['All conditions', '全部满足'],
        any: ['Any condition', '任一满足'],
        not: ['Invert condition', '取反'],
        eq: ['Equals', '等于'],
        ne: ['Does not equal', '不等于'],
        exists: ['Field exists', '字段存在'],
        not_exists: ['Field is missing', '字段不存在'],
        contains: ['Contains', '包含'],
        not_contains: ['Does not contain', '不包含'],
        starts_with: ['Starts with', '开头为'],
        ends_with: ['Ends with', '结尾为'],
        in: ['In set', '属于集合'],
        not_in: ['Not in set', '不属于集合'],
        regex: ['Matches pattern', '匹配正则'],
        not_regex: ['Does not match pattern', '不匹配正则'],
        gt: ['Greater than', '大于'],
        gte: ['At least', '大于等于'],
        lt: ['Less than', '小于'],
        lte: ['At most', '小于等于'],
        type: ['Value type', '值类型'],
    },
    action: {
 sequence:['Sequence','顺序执行'],if:['Branch','条件分支'],for_each:['For each','逐项处理'],walk:['Walk subtree','递归遍历'],let:['Variable','保存变量'],scope:['Fragments','规则片段'],call:['Call fragment','调用片段'],
        rewrite_model: ['Change model', '修改模型'],
        drop_environment_context: ['Remove environment context', '清理环境上下文'],
        drop_input_items: ['Remove input items', '删除输入项'],
        drop_tools: ['Remove tools', '删除工具'],
        passthrough_fields: ['Restore client fields', '补入客户端字段'],
        set_reasoning: ['Set reasoning', '设置推理参数'],
        json_set: ['Set field value', '设置字段值'],
        json_remove: ['Remove fields', '删除指定字段'],
        json_merge: ['Merge object', '合并对象'],
        json_transfer: ['Copy or move field', '复制或移动字段'],
        array_insert: ['Insert array items', '插入数组元素'],
        array_filter: ['Filter array', '筛选数组'],
        text_replace: ['Replace text', '替换文本'],
        reject_request: ['Block request', '阻断请求'],
        drop_event: ['Drop response event', '丢弃响应事件'],
    },
    phase: {
 client_request:['Client input','客户端输入'],request_normalize:['Request construction','请求构建'],request_finalize:['Protocol fields','协议字段'],upstream_headers:['Upstream headers','发送前请求头'],
        request: ['Request rule', '请求规则'],
        response_event: ['Response event rule', '响应事件规则'],
        response_body: ['Response body rule', '响应正文规则']
    },
    source: {
 original:['Stage original','阶段原始输入'],vars:['Local variables','局部变量'],protocol:['Protocol rules','协议规则'],system:['System','系统'],
        current: ['Current payload', '当前载荷'],
        client: ['Original client payload', '客户端原始载荷'],
        context: ['Context facts', '上下文事实'],
        item: ['Array item', '当前数组元素'],
        user: ['Custom rule', '自定义规则'],
        custom: ['Custom rule', '自定义规则'],
        builtin: ['Built-in rule', '内置规则'],
        built_in: ['Built-in rule', '内置规则'],
        legacy: ['Migrated rule', '迁移规则'],
        migrated: ['Migrated rule', '迁移规则']
    },
    status: {
        matched: ['Matched', '已命中'],
        not_matched: ['Not matched', '未命中'],
        skipped: ['Skipped', '已跳过'],
        short_circuited: ['Short-circuited', '短路跳过'],
        not_executed: ['Not executed', '未执行'],
        success: ['Succeeded', '执行成功'],
        changed: ['Changed', '已修改'],
        unchanged: ['No change', '无变化'],
        no_change: ['No change', '无变化'],
        error: ['Failed', '失败'],
        failed: ['Failed', '失败'],
        rolled_back: ['Rolled back', '已回滚'],
        blocked: ['Request blocked', '请求已阻断'],
        dropped: ['Event dropped', '事件已丢弃'],
        enabled: ['Enabled', '已启用'],
        disabled: ['Disabled', '已停用'],
        stale: ['Outdated result', '结果已过期'],
        pending: ['Not simulated', '尚未模拟']
    },
    field: {
        schema_version: ['Language version', '语言版本'],
        id: ['Identifier', '标识'],
        name: ['Name', '名称'],
        description: ['Description', '说明'],
        enabled: ['Enabled', '启用'],
        priority: ['Priority', '优先级'],
        phase: ['Execution phase', '执行阶段'],
        when: ['Conditions', '条件'],
        actions: ['Ordered actions', '有序动作'],
        stop_after_match: ['Stop after match', '命中后停止'],
        on_error: ['Error policy', '错误策略'],
        revision: ['Revision', '修订号'],
        order_index: ['Stable order', '稳定顺序'],
        created_at: ['Created at', '创建时间'],
        updated_at: ['Updated at', '更新时间'],
        legacy_name: ['Migration name', '迁移名称'],
        op: ['Condition operator', '条件操作'],
        conditions: ['Child conditions', '子条件'],
        source: ['Data source', '数据来源'],
        path: ['Field path', '字段路径'],
        encoding: ['Value encoding', '取值编码'],
        value: ['Value', '值'],
        values: ['Values', '值列表'],
        pattern: ['Pattern', '匹配模式'],
        case_insensitive: ['Ignore case', '忽略大小写'],
        dot_all: ['Dot matches newlines', '点号匹配换行'],
        multiline: ['Multiline matching', '多行匹配'],
        model: ['Current model', '当前模型'],
        original_model: ['Original model', '原始模型'],
        request_path: ['Request path', '请求路径'],
        request_method: ['Request method', '请求方法'],
        api_key_id: ['API key identity', 'API Key 身份'],
        client_protocol: ['Client protocol', '客户端协议'],
        account_id: ['Selected account', '所选账号'],
        upstream_protocol: ['Upstream protocol', '上游协议'],
        event_type: ['Event type', '事件类型'],
        item_index: ['Original item index', '元素原始序号'],
        content_item_kind: ['Content item kind', '内容项类型'],
        also_strip_from_instructions: ['Also clean instructions', '同时清理指令'],
        types: ['Item types', '输入项类型'],
        target: ['Match target', '匹配目标'],
        names: ['Tool names', '工具名称'],
        drop_all: ['Remove all', '全部删除'],
        fields: ['Field names', '字段名称'],
        effort: ['Reasoning effort', '推理强度'],
        summary: ['Reasoning summary', '推理摘要'],
        create_parents: ['Create parent objects', '创建父对象'],
        if_exists: ['If present', '已存在时'],
        paths: ['Field paths', '字段路径列表'],
        on_missing: ['If missing', '缺失时'],
        mode: ['Operation mode', '操作方式'],
        array_mode: ['Array merge mode', '数组合并方式'],
        source_path: ['Source field path', '来源字段路径'],
        target_path: ['Target field path', '目标字段路径'],
        operation: ['Operation', '操作'],
        overwrite: ['Overwrite target', '覆盖目标'],
        position: ['Insert position', '插入位置'],
        index: ['Item index', '元素序号'],
        create_if_missing: ['Create if missing', '缺失时创建'],
        predicate: ['Item conditions', '数组元素条件'],
        match: ['Match mode', '匹配方式'],
        replacement: ['Replacement text', '替换文本'],
        replace_all: ['Replace all matches', '替换全部匹配'],
        status: ['HTTP status', 'HTTP 状态码'],
        message: ['Message', '提示信息'],
    },
    option: {
        abort: ['Abort execution', '中止执行'],
        skip_rule: ['Roll back and skip rule', '回滚并跳过规则'],
        value: ['Keep value type', '保留值类型'],
        json: ['JSON text', 'JSON 文本'],
        text: ['Plain text', '纯文本'],
        ignore: ['Ignore missing', '忽略缺失'],
        error: ['Fail on missing', '缺失时报错'],
        overwrite: ['Overwrite', '覆盖'],
        keep: ['Keep existing', '保留已有值'],
        shallow: ['Shallow merge', '浅合并'],
        deep: ['Recursive merge', '递归合并'],
        replace: ['Replace array', '替换数组'],
        append: ['Append', '追加'],
        prepend: ['Prepend', '前插'],
        index: ['At index', '指定序号'],
        copy: ['Copy', '复制'],
        move: ['Move', '移动'],
        remove_matches: ['Remove matching items', '删除命中项'],
        keep_matches: ['Keep matching items', '保留命中项'],
        literal: ['Exact text', '精确文本'],
        regex: ['Regular expression', '正则表达式'],
        null: ['Null', '空值'],
        boolean: ['Boolean', '布尔值'],
        number: ['Number', '数字'],
        string: ['String', '字符串'],
        array: ['Array', '数组'],
        object: ['Object', '对象'],
    },
    expression: {
        literal: ['Literal JSON', 'JSON 字面量'],
        reference: ['Field reference', '字段引用'],
        literal_escape: ['Escaped literal', '转义字面量']
    },
}
const legacyRuleActions: Record<string, string> = {
    drop_environment_context: 'drop_environment_context',
    drop_input_items: 'drop_input_items',
    drop_tools: 'drop_tools',
    drop_fields: 'json_remove',
    rewrite_model: 'rewrite_model',
    passthrough_fields: 'passthrough_fields',
    set_reasoning: 'set_reasoning',
    block_prompt: 'reject_request',
}

/** Presentation only: never mutate the stored name, even when it is localized. */
export function ruleDisplayName(rule: Pick<Rule, 'name' | 'source' | 'legacy_name'>, locale: string): string {
    if (rule.source === 'legacy' && rule.legacy_name === rule.name && Object.hasOwn(legacyRuleActions, rule.name)) return ruleLabel('action', legacyRuleActions[rule.name]!, locale)
    return rule.name
}

export function ruleLabel(group: string, value: string, locale: string): string {
    return ruleLabels[group]?.[value]?.[locale === 'zh-CN' ? 1 : 0] ?? value
}

export function ruleOptionLabel(value: string, locale: string): string {
    for (const group of ['option', 'phase', 'source', 'condition']) if (ruleLabels[group]?.[value]) return ruleLabel(group, value, locale)
    return value
}

export function localizedConditionSummary(condition: RuleCondition, locale: string): string {
    const label = ruleLabel('condition', condition.op, locale)
    return condition.conditions ? `${label} (${condition.conditions.map(c => localizedConditionSummary(c, locale)).join(' · ')})` : `${label}${condition.path ? ` · ${condition.path}` : ''}`
}
