package store

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/stdlib"
)

func TestPostgresPlaceholders(t *testing.T) {
	input := "SELECT ?, '?', 'it''s ?', \"?\", $$?$$, $body$?$body$, ??, ? -- ?\n/* ? /* ? */ ? */ WHERE id=?"
	want := "SELECT $1, '?', 'it''s ?', \"?\", $$?$$, $body$?$body$, ?, $2 -- ?\n/* ? /* ? */ ? */ WHERE id=$3"
	if got := postgresPlaceholders(input); got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
	if got := (&Store{driver: "sqlite"}).Rebind(input); got != input {
		t.Fatalf("SQLite SQL changed: %q", got)
	}
}

func TestPostgresProxyTriggerDollarQuotes(t *testing.T) {
	functions := 0
	for _, statement := range postgresProxyBindingSchema {
		if !strings.Contains(statement, "CREATE OR REPLACE FUNCTION") {
			continue
		}
		functions++
		if strings.Count(statement, "$proxy$") != 2 || !strings.Contains(statement, "AS $proxy$") || !strings.HasSuffix(strings.TrimSpace(statement), "END; $proxy$") {
			t.Fatalf("unclosed PL/pgSQL function quote: %q", statement)
		}
	}
	if functions != 2 {
		t.Fatalf("function count=%d", functions)
	}
}

func TestPostgresConnectionErrorDoesNotLeakDSN(t *testing.T) {
	// Invalid connect_timeout is rejected during parsing, before any network dial.
	for _, dsn := range []string{
		"postgres://user:secret-user@example.invalid/db?password=secret-query&connect_timeout=bad",
		"host=example.invalid password=secret-keyword connect_timeout=bad",
	} {
		s, err := OpenOptions(Options{Driver: "postgres", DSN: dsn})
		if err == nil {
			s.Close()
			t.Fatal("invalid DSN accepted")
		}
		if strings.Contains(err.Error(), "secret") || strings.Contains(err.Error(), "example.invalid") || strings.Contains(err.Error(), "password") {
			t.Fatalf("leaked DSN: %v", err)
		}
		if !strings.Contains(err.Error(), "invalid connection configuration") {
			t.Fatalf("classification=%v", err)
		}
		if errors.Unwrap(err) != nil {
			t.Fatal("sanitized error retains secret-bearing cause")
		}
	}
	for _, phase := range []string{"open", "begin migration"} {
		err := postgresConnectionError(phase, errors.New("password=secret-connect"))
		if strings.Contains(err.Error(), "secret") || !strings.Contains(err.Error(), "connection failed") || errors.Unwrap(err) != nil {
			t.Fatalf("unsanitized connection failure: %v", err)
		}
	}
}

func TestPostgresDialect(t *testing.T) {
	s := &Store{driver: "postgres"}
	q := s.Rebind("SELECT " + accountColumns + " FROM accounts WHERE id=?")
	for _, bad := range []string{"json_group_array", "json_object(", "json(g.", "id=?"} {
		if strings.Contains(q, bad) {
			t.Errorf("PostgreSQL account SQL contains %q: %s", bad, q)
		}
	}
	if !strings.Contains(q, "json_agg(group_id ORDER BY group_id)") || !strings.Contains(q, "id=$1") {
		t.Fatal(q)
	}
	for input, want := range map[string]string{
		"instr(lower(name),lower(?))":                 "strpos(lower(name),lower($1))",
		"MAX(cooldown_until,?)":                       "GREATEST(cooldown_until,$1)",
		"CAST(count(*)*0.95 AS INTEGER)":              "CAST(FLOOR(count(*)*0.95) AS BIGINT)",
		"CAST(AVG(NULLIF(duration_ms,0)) AS INTEGER)": "CAST(TRUNC(AVG(NULLIF(duration_ms,0))) AS BIGINT)",
	} {
		if got := s.Rebind(input); got != want {
			t.Errorf("%s => %s, want %s", input, got, want)
		}
	}
	schema := postgresSchema(schemaSQL)
	for _, bad := range []string{"AUTOINCREMENT", "INTEGER", "REAL"} {
		if strings.Contains(schema, bad) {
			t.Errorf("schema contains %s", bad)
		}
	}
	if strings.Count(schema, "GENERATED BY DEFAULT AS IDENTITY") != 7 {
		t.Fatal("missing identity columns")
	}
	if !errors.Is(groupWriteError(&pgconn.PgError{Code: "23505", ConstraintName: "account_groups_name_key"}), ErrGroupNameConflict) {
		t.Fatal("PostgreSQL unique error not translated")
	}
}

func TestOpenOptionsValidation(t *testing.T) {
	for _, opts := range []Options{{}, {Driver: "mysql", Path: "ignored"}, {Driver: "postgres", Path: "must-not-be-a-dsn"}} {
		if s, err := OpenOptions(opts); err == nil {
			s.Close()
			t.Fatalf("accepted %+v", opts)
		}
	}
}

func TestOpenOptionsPoolFields(t *testing.T) {
	path := storeTestPath(t)
	s, err := OpenOptions(Options{Path: path, MaxOpenConns: 3, MaxIdleConns: 9, ConnMaxLifetime: time.Minute})
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	stats := s.DB().Stats()
	if stats.MaxOpenConnections != 3 {
		t.Fatalf("max open=%d", stats.MaxOpenConnections)
	}
	if err := s.DB().Ping(); err != nil {
		t.Fatal(err)
	}
}

func TestOpenOptionsRejectsNegativePoolFields(t *testing.T) {
	for _, opts := range []Options{{Path: storeTestPath(t), MaxOpenConns: -1}, {Path: storeTestPath(t), MaxIdleConns: -1}, {Path: storeTestPath(t), ConnMaxLifetime: -time.Second}} {
		if s, err := OpenOptions(opts); err == nil {
			s.Close()
			t.Fatalf("accepted negative options: %+v", opts)
		}
	}
}

func TestOpenOptionsSQLite(t *testing.T) {
	path := storeTestPath(t)
	s, err := OpenOptions(Options{DSN: path, Path: filepath.Join(t.TempDir(), "ignored.db")})
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	if s.Driver() != "sqlite" {
		t.Fatal(s.Driver())
	}
	exerciseSQLBackend(t, s)
}

func TestSingleConnectionLegacyMigrationCompletes(t *testing.T) {
	const childPathEnv = "PI_GATEWAY_TEST_SINGLE_CONNECTION_LEGACY_PATH"
	if path := os.Getenv(childPathEnv); path != "" {
		s, err := OpenOptions(Options{Path: path, MaxOpenConns: 1, MaxIdleConns: 1, ConnMaxLifetime: time.Minute})
		if err != nil {
			t.Fatal(err)
		}
		defer s.Close()
		if limit := s.DB().Stats().MaxOpenConnections; limit != 1 {
			t.Fatalf("runtime connection limit=%d", limit)
		}
		if _, err := s.ListKeys(context.Background()); err != nil {
			t.Fatal(err)
		}
		backups, err := filepath.Glob(path + ".bak-*")
		if err != nil || len(backups) != 1 {
			t.Fatalf("legacy backups=%v err=%v", backups, err)
		}
		return
	}
	path := storeTestPath(t)
	db := makeLegacyPool(t, path)
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}
	// Bound the regression in a child process so a pool deadlock cannot leave
	// an uninterruptible goroutine holding this test's SQLite fixture open.
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, os.Args[0], "-test.run=^TestSingleConnectionLegacyMigrationCompletes$", "-test.v")
	cmd.Env = append(os.Environ(), childPathEnv+"="+path)
	output, err := cmd.CombinedOutput()
	if ctx.Err() != nil {
		t.Fatalf("single-connection migration did not finish in time: %v\n%s", ctx.Err(), output)
	}
	if err != nil {
		t.Fatalf("legacy migration subprocess: %v\n%s", err, output)
	}
}

func TestSQLiteMigrationConnectionErrorKeepsCause(t *testing.T) {
	s := openTestStore(t)
	if err := s.Close(); err != nil {
		t.Fatal(err)
	}
	err := s.migrateOnce()
	if err == nil || !strings.Contains(err.Error(), "SQLite migration connection") || errors.Unwrap(err) == nil {
		t.Fatalf("SQLite connection error lost classification/cause: %v", err)
	}
}

func TestPostgresSchemaVersionLedgerOffline(t *testing.T) {
	// The small version ledger uses portable SQL; exercise its real transaction
	// behavior on SQLite without requiring a PostgreSQL service locally.
	s := openTestStore(t)
	ctx := context.Background()
	tx, err := s.DB().BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	if version, err := checkPostgresSchemaVersion(ctx, tx); err != nil || version != 0 {
		t.Fatalf("fresh version=%d err=%v", version, err)
	}
	if err := recordPostgresSchemaVersion(ctx, tx); err != nil {
		t.Fatal(err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatal(err)
	}
	tx, err = s.DB().BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	if version, err := checkPostgresSchemaVersion(ctx, tx); err != nil || version != postgresSchemaVersion {
		t.Fatalf("persisted version=%d err=%v", version, err)
	}
	var appliedAt int64
	if err := tx.QueryRowContext(ctx, `SELECT applied_at FROM schema_migrations WHERE version=$1`, postgresSchemaVersion).Scan(&appliedAt); err != nil || appliedAt <= 0 {
		t.Fatalf("applied_at=%d err=%v", appliedAt, err)
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO schema_migrations(version,applied_at) VALUES ($1,$2)`, postgresSchemaVersion+1, NowMS()); err != nil {
		t.Fatal(err)
	}
	if _, err := checkPostgresSchemaVersion(ctx, tx); err == nil || !strings.Contains(err.Error(), "newer than supported") {
		t.Fatalf("accepted future schema: %v", err)
	}
	if err := tx.Rollback(); err != nil {
		t.Fatal(err)
	}
	var version int64
	if err := s.DB().QueryRow(`SELECT MAX(version) FROM schema_migrations`).Scan(&version); err != nil || version != postgresSchemaVersion {
		t.Fatalf("rollback version=%d err=%v", version, err)
	}
}

func TestSQLiteDSNPreservesLegacyBackup(t *testing.T) {
	path := storeTestPath(t)
	db := makeLegacyPool(t, path)
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}
	s, err := OpenOptions(Options{DSN: path + "?cache=private"})
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	if s.path != path {
		t.Fatalf("snapshot path=%q want %q", s.path, path)
	}
	backups, err := filepath.Glob(path + ".bak-*")
	if err != nil || len(backups) != 1 {
		t.Fatalf("backups=%v err=%v", backups, err)
	}
}

func TestOpenMemoryUsesSingleDatabase(t *testing.T) {
	s, err := OpenOptions(Options{Path: ":memory:", MaxOpenConns: 8, MaxIdleConns: 8, ConnMaxLifetime: time.Nanosecond})
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	if got := s.DB().Stats().MaxOpenConnections; got != 1 {
		t.Fatalf("memory pool=%d", got)
	}
	exerciseSQLBackend(t, s)
}

// PostgreSQL is optional locally. CI may supply a disposable database with
// CREATE SCHEMA privileges; each run creates and drops only its own schema.
func TestPostgresStoreIntegration(t *testing.T) {
	dsn := os.Getenv("PI_GATEWAY_TEST_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("PI_GATEWAY_TEST_POSTGRES_DSN is not set")
	}
	cfg, err := pgx.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	admin := stdlib.OpenDB(*cfg)
	defer admin.Close()
	schema := "store_test_" + strings.TrimPrefix(GenerateKey(), "sk-pi-")
	if _, err := admin.Exec(`CREATE SCHEMA ` + schema); err != nil {
		t.Fatal(err)
	}
	defer func() {
		if _, err := admin.Exec(`DROP SCHEMA ` + schema + ` CASCADE`); err != nil {
			t.Error(err)
		}
	}()
	cfg.RuntimeParams["search_path"] = schema
	registered := stdlib.RegisterConnConfig(cfg)
	defer stdlib.UnregisterConnConfig(registered)
	s, err := OpenOptions(Options{Driver: "postgresql", DSN: registered})
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	if s.Driver() != "postgres" {
		t.Fatal(s.Driver())
	}
	exerciseSQLBackend(t, s)
	exerciseAccountModelBatches(t, s)
	second, err := OpenOptions(Options{Driver: "postgres", DSN: registered})
	if err != nil {
		t.Fatal(err)
	}
	defer second.Close()
	exerciseCatalogRevisions(t, s, second)
	if err := s.migrate(); err != nil {
		t.Fatalf("idempotent migration: %v", err)
	}
	var version, count int64
	if err := s.DB().QueryRow(`SELECT MAX(version),COUNT(*) FROM schema_migrations`).Scan(&version, &count); err != nil || version != postgresSchemaVersion || count != 1 {
		t.Fatalf("version=%d count=%d err=%v", version, count, err)
	}
	if _, err := s.ExecContext(context.Background(), `INSERT INTO schema_migrations(version,applied_at) VALUES (?,?)`, postgresSchemaVersion+1, NowMS()); err != nil {
		t.Fatal(err)
	}
	future, err := OpenOptions(Options{Driver: "postgres", DSN: registered})
	if err == nil {
		future.Close()
		t.Fatal("newer PostgreSQL schema accepted")
	}
	if !strings.Contains(err.Error(), "newer than supported") {
		t.Fatalf("unexpected future schema error: %v", err)
	}
	if err := s.DB().QueryRow(`SELECT MAX(version) FROM schema_migrations`).Scan(&version); err != nil || version != postgresSchemaVersion+1 {
		t.Fatalf("future schema changed on refusal: version=%d err=%v", version, err)
	}
}

func exerciseSQLBackend(t *testing.T, s *Store) {
	t.Helper()
	ctx := context.Background()
	p := &Proxy{Name: "test proxy", URL: "http://user:secret@localhost:8080"}
	if err := s.CreateProxy(ctx, p); err != nil {
		t.Fatal(err)
	}
	a := &Account{Name: "account", Enabled: true, ProxyID: &p.ID, ProxyURL: "stale"}
	if err := s.CreateAccount(ctx, a); err != nil {
		t.Fatal(err)
	}
	g := &AccountGroup{Name: "group", Enabled: true, AccountIDs: []int64{a.ID}, DisabledModels: []string{"blocked"}}
	if err := s.CreateAccountGroup(ctx, g); err != nil {
		t.Fatal(err)
	}
	k := &APIKey{Name: "key", Enabled: true, GroupIDs: []int64{g.ID}}
	if err := s.CreateKey(ctx, k); err != nil {
		t.Fatal(err)
	}
	if a.ID <= 0 || p.ID <= 0 || g.ID <= 0 || k.ID <= 0 {
		t.Fatal("missing generated IDs")
	}
	got, err := s.GetAccount(ctx, a.ID)
	if err != nil || got == nil || got.ProxyURL != p.URL || len(got.GroupIDs) != 1 || len(got.InheritedModelRestrictions) != 1 {
		t.Fatalf("account=%+v, err=%v", got, err)
	}
	if err := s.MarkAccountUsed(ctx, a.ID, true); err != nil {
		t.Fatal(err)
	}
	// Exercise the production scheduling escape hatch with boolean and fractional values.
	if _, err := s.ExecContext(ctx, `UPDATE accounts SET
		cooldown_until=CASE WHEN ? THEN MAX(cooldown_until,?) ELSE cooldown_until END,
		ewma_first_output_ms=CASE WHEN CAST(? AS DOUBLE PRECISION)<=0 THEN ewma_first_output_ms ELSE ? END
		WHERE id=?`, true, NowMS(), 12.5, 12.5, a.ID); err != nil {
		t.Fatal(err)
	}
	p.URL = "http://localhost:8081"
	if err := s.UpdateProxy(ctx, p); err != nil {
		t.Fatal(err)
	}
	got, err = s.GetAccount(ctx, a.ID)
	if err != nil || got.ProxyURL != p.URL || got.ErrorCount != 1 {
		t.Fatalf("updated account=%+v err=%v", got, err)
	}
	if _, _, err := s.ListProxies(ctx, "localhost", 10, 0); err != nil {
		t.Fatal(err)
	}
	if err := s.PatchAccountManagementFields(ctx, a.ID, AccountManagementPatch{GroupIDs: []int64{999999}}); err == nil {
		t.Fatal("invalid group accepted")
	}
	got, err = s.GetAccount(ctx, a.ID)
	if err != nil || len(got.GroupIDs) != 1 {
		t.Fatalf("transaction not rolled back: %+v %v", got, err)
	}
	catalog := &ModelCatalog{Models: []CatalogModel{{ID: "model"}}, FetchedAt: NowMS(), AttemptedAt: NowMS()}
	if err := s.SaveAccountModelCatalog(ctx, a.ID, catalog); err != nil {
		t.Fatal(err)
	}
	if err := s.SaveAccountModelCatalog(ctx, a.ID, catalog); err != nil {
		t.Fatal(err)
	}
	if _, err := s.GetAccountModelCatalog(ctx, a.ID); err != nil {
		t.Fatal(err)
	}
	if err := s.SetSecret(ctx, "test.secret", "value"); err != nil {
		t.Fatal(err)
	}
	if err := s.SaveSettings(ctx, &Settings{DefaultModel: "model"}); err != nil {
		t.Fatal(err)
	}
	if _, err := s.LoadSettings(ctx, nil); err != nil {
		t.Fatal(err)
	}
	if err := s.UpsertMiddleware(ctx, &MiddlewareRow{Name: "test", Enabled: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := s.ListMiddlewares(ctx); err != nil {
		t.Fatal(err)
	}
	if err := s.RecordAudit(ctx, "test", "detail"); err != nil {
		t.Fatal(err)
	}
	if _, err := s.ListAudit(ctx, 10); err != nil {
		t.Fatal(err)
	}
	now := NowMS()
	for i := 0; i < 2; i++ {
		settled, err := s.SettleKeyCharge(ctx, "charge", k.ID, 10, now)
		if err != nil || settled != (i == 0) {
			t.Fatalf("settled=%v err=%v", settled, err)
		}
	}
	if windows, err := s.KeyBudgetStatus(ctx, k.ID, now); err != nil || windows[0].UsedMicros != 10 {
		t.Fatalf("windows=%v err=%v", windows, err)
	}
	for _, latency := range []int64{10, 11} {
		c := &Capture{AccountID: a.ID, Outcome: OutcomeOK, DurationMS: latency}
		if err := s.InsertCapture(ctx, c, 50); err != nil || c.ID <= 0 {
			t.Fatalf("capture=%+v err=%v", c, err)
		}
	}
	if stats, err := s.Stats(ctx, 50); err != nil || stats.AvgMS != 10 {
		t.Fatalf("capture stats=%+v err=%v", stats, err)
	}
	for _, ttft := range []int64{100, 200, 300} {
		finishTestUsage(t, s, UsageRecord{RequestID: "usage", APIKeyID: k.ID, AccountID: a.ID, Model: "model", Outcome: "succeeded", StartedAt: now, FirstTokenMS: ttft, LatencyMS: 1000, OutputTokens: usageInt(10)})
	}
	summary, err := s.UsageSummaryFor(ctx, UsageFilter{})
	if err != nil || summary.RequestCount != 3 || summary.TTFT.P50 != 200 || summary.TTFT.P95 != 300 {
		t.Fatalf("summary=%+v err=%v", summary, err)
	}
	if _, n, err := s.ListUsageRecords(ctx, UsageFilter{Search: "USAGE", Limit: 2}); err != nil || n != 3 {
		t.Fatalf("usage count=%d err=%v", n, err)
	}
	if _, err := s.UsageTrend(ctx, UsageFilter{}, "hour"); err != nil {
		t.Fatal(err)
	}
	if _, err := s.UsageByModel(ctx, UsageFilter{}); err != nil {
		t.Fatal(err)
	}
	if _, err := s.UsageByKey(ctx, UsageFilter{}); err != nil {
		t.Fatal(err)
	}
	if _, err := s.UsageByAccount(ctx, UsageFilter{}); err != nil {
		t.Fatal(err)
	}
}
